-- USER SQL
CREATE USER Muffin IDENTIFIED BY 1234 ;

-- QUOTAS

-- ROLES
GRANT "DBA" TO Muffin ;
GRANT "CONNECT" TO Muffin ;
GRANT "RESOURCE" TO Muffin ;

-- SYSTEM PRIVILEGES

CREATE TABLE MUSER 
(
  USERID NUMBER NOT NULL 
, PW VARCHAR2(20) NOT NULL 
, USERNAME VARCHAR2(20) NOT NULL 
, CONSTRAINT MUSER_PK PRIMARY KEY 
  (
    USERID 
  )
  ENABLE 
);
